from tkinter import *
root = Tk()
root.title("Made up College")
def get_results():
    first_name = E1.get()
    last_name = E2.get()
    age_value = E3.get()
    course = E4.get()
    course_code = E5.get()
    grade = E6.get()
   
    file = open("madeupcollege.txt", "a")
    file.write(first_name + ":" + last_name + ":" + age_value + ":" + course + ":" + course_code + ":" + grade + "\n")
    file.close()

L1 = Label(root, text="First Name:") 
L1.grid(column=0, row=1)
E1 = Entry(root)
E1.grid(column=1, row=1)
L2 = Label(root, text="Last Name:" )
L2.grid(column=0, row=2)
E2 = Entry(root)
E2.grid(column=1, row =2)
L3 = Label(root, text="Age:")
L3.grid(column=0, row=3)
E3 = Entry(root)
E3.grid(column=1, row=3)
L4 = Label(root, text="Course:")
L4.grid(column=0, row=4)
E4 = Entry(root)
E4.grid(column=1, row=4)
L5 = Label(root, text="Course Code:")
L5.grid(column=0, row=5)
E5 = Entry(root)
E5.grid(column=1, row=5)
L6 = Label(root, text="Grade:")
L6.grid(column=0, row=6)
E6 = Entry(root)
E6.grid(column=1, row=6)
 
process_button = Button(root, text="Process", command=get_results)
process_button.grid(column=0, row=7)

root.mainloop()